import { BUILD_ID } from '@/lib/build-id';

/**
 * The service worker, served from a route so it can carry the build id.
 *
 * It replaced `public/sw.js`, whose comment said precaching was unsafe because
 * Next emits hashed bundle URLs that change every build, so a stale cache would
 * silently break the app for installed users. **That argument is against
 * PRECACHING, and this is not precaching** — see the rules below. The route form
 * is the same one `app/.well-known/assetlinks.json/` uses, and it is needed for
 * one reason: a file in `public/` is static bytes and cannot know which build it
 * belongs to, so it could never clean up after an older deploy.
 *
 * `public/sw.js` had to be DELETED rather than left alongside this: a file in
 * `public/` wins over a route at the same path, so leaving it would have made
 * this route dead code that looked live.
 *
 * The path stays `/sw.js` because that is what is already registered on every
 * installed device. A service worker's scope is its own directory, so `/sw.js`
 * scopes to `/` and needs no `Service-Worker-Allowed` header.
 */

// `force-dynamic` so the body is regenerated rather than baked into a static
// export — the build id has to be the one this deploy was built with.
export const dynamic = 'force-dynamic';

const source = (buildId: string) => `// Generated by app/sw.js/route.ts — do not edit a copy of this by hand.
const VERSION = ${JSON.stringify(buildId)};
const STATIC = 'bmb-sw-static-' + VERSION;
const PAGES = 'bmb-sw-pages-' + VERSION;
const MINE = [STATIC, PAGES];

// The last resort, and it should be unreachable: install precaches '/'. Kept
// because the alternative at this point is rejecting, and a navigation that
// rejects is the error screen this whole branch exists to avoid.
const OFFLINE_HTML = '<!doctype html><meta charset=utf-8>'
  + '<meta name=viewport content="width=device-width,initial-scale=1">'
  + '<title>Offline</title>'
  + '<body style="margin:0;display:grid;place-items:center;height:100vh;'
  + 'font:16px system-ui;background:#0b0b0d;color:#f4efe6">'
  + '<p>No connection, and this page was not saved.</p>';

self.addEventListener('install', (event) => {
  // TWO documents are precached, and no more.
  //
  // Everything else still fills from real traffic. This exists because the
  // FIRST load of a page is fetched BEFORE this worker controls it, so it never
  // passes through the fetch handler and never enters PAGES. A visitor who
  // installs the app and then loses signal without loading a second time had no
  // shell at all — measured on an iPhone, and it did not degrade, it produced
  // "FetchEvent.respondWith received an error: TypeError: Load failed".
  //
  // It does not weaken network-first. '/' is still fetched fresh on every load
  // that has a connection; this copy is only ever reached when the fetch
  // rejects. And it cannot go stale across a deploy: PAGES carries the build id,
  // so a new worker precaches its own '/' and activate() deletes the old one.
  event.waitUntil((async () => {
    // '/downloads' is here for its own reason, not for symmetry: it is the one
    // route whose entire PURPOSE is to work without a network, and a dock tab
    // that does nothing is the worst way to find that out. A client-side route
    // change fetches an RSC payload rather than a document, so when that fetch
    // fails the router falls back to a real navigation — and that navigation
    // has to land on the route's OWN document. Without this it landed on the
    // shell, which is the home page's HTML under a /downloads URL.
    //
    // Reported from an iPhone: the tab did not open in airplane mode and was
    // fine on wifi. It does not reproduce in headless Chrome, which prefetches
    // every dock <Link> on the first load and so always has what the tap needs.
    for (const path of ['/', '/downloads']) {
      try {
        const cache = await caches.open(PAGES);
        await cache.add(path);
      } catch (e) {
        // An install must never fail on this. Without it the app simply has no
        // offline shell until the next load, which is where this started.
      }
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Delete every cache this worker owns from an older build. The prefix test
    // is deliberately narrow: the DOWNLOADS buckets (bmb-downloads-*) are the
    // user's own files and must never be touched here.
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((n) => n.startsWith('bmb-sw-') && !MINE.includes(n))
        .map((n) => caches.delete(n)),
    );
    await self.clients.claim();
  })());
});

/** Four things never enter a cache, and each would be a real bug. */
function cacheable(request, url) {
  // A cached POST is not a thing.
  if (request.method !== 'GET') return false;
  // Enclosure audio, relay traffic, third-party artwork. Not ours to hold, and
  // downloads have their own buckets with their own lifetime.
  if (url.origin !== self.location.origin) return false;
  // A cached /api/feed serves a stale episode list, and /api/live-status would
  // report a finished show as live.
  if (url.pathname.startsWith('/api/')) return false;
  return true;
}

async function putIfOk(cacheName, request, response) {
  // A cached 404 or 502 outlives the outage that produced it. An opaque or
  // cross-origin response cannot be read back usefully either.
  if (!response || !response.ok || response.type !== 'basic') return;
  if ((response.headers.get('cache-control') || '').includes('no-store')) return;
  const cache = await caches.open(cacheName);
  await cache.put(request, response.clone());
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (!cacheable(request, url)) return; // straight to the network, as before

  // /_next/static/* is CONTENT-HASHED, so a given URL's bytes never change and
  // a cached copy cannot go stale. Cache-first here is what makes the rule
  // below work offline: the last document's chunks are still present.
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith((async () => {
      const hit = await caches.match(request);
      if (hit) return hit;
      const res = await fetch(request);
      await putIfOk(STATIC, request, res);
      return res;
    })());
    return;
  }

  // EVERYTHING ELSE IS NETWORK-FIRST, and the cache is used ONLY when the fetch
  // rejects. A reader with a connection is therefore never served a stale
  // document, so a stale document can never reference dead chunk hashes while
  // online — which is the failure the old public/sw.js comment warned about.
  event.respondWith((async () => {
    try {
      const res = await fetch(request);
      await putIfOk(PAGES, request, res);
      return res;
    } catch (err) {
      const hit = await caches.match(request);
      if (hit) return hit;

      // A NAVIGATION MUST NEVER REJECT HERE. Rejecting inside respondWith does
      // not fall back to the browser's own offline page — it replaces it with
      // "FetchEvent.respondWith received an error: TypeError: Load failed",
      // which is a worse screen than having no service worker at all. So a
      // navigation that missed its exact URL falls back to the shell: the app
      // reads its own deep-link parameters off window.location on mount, so
      // '/?podcast=…' served the shell still lands where the reader meant.
      if (request.mode === 'navigate') {
        const shell = await caches.match('/');
        if (shell) return shell;
        return new Response(OFFLINE_HTML, {
          status: 503,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        });
      }

      // A SUBRESOURCE is the opposite: rejecting is exactly what would happen
      // with no worker installed, and it is what the app's own catch blocks are
      // written against. Synthesising a Response here would turn a network
      // failure into a non-ok ANSWER, and lib/downloads/downloads-cache.ts's
      // fetchDoc reads the difference — it falls back to a downloaded copy only
      // on a rejection.
      throw err;
    }
  })());
});
`;

export function GET() {
  return new Response(source(BUILD_ID), {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      // Browsers cap a service worker script at 24h regardless, but say it
      // plainly: this file must be re-read, or a deploy's cleanup never runs.
      'Cache-Control': 'no-cache, must-revalidate',
    },
  });
}
