import { BUILD_ID } from '@/lib/build-id';

/**
 * The service worker, served from a route so it can carry the build id.
 *
 * It replaced `public/sw.js`, whose comment said precaching was unsafe because
 * Next emits hashed bundle URLs that change every build, so a stale cache would
 * silently break the app for installed users. **That argument is against
 * PRECACHING, and this is not precaching** — see the rules below. The route form
 * is the same one `app/.well-known/assetlinks.json/` uses, and it is needed for
 * one reason: a file in `public/` is static bytes and cannot know which build it
 * belongs to, so it could never clean up after an older deploy.
 *
 * `public/sw.js` had to be DELETED rather than left alongside this: a file in
 * `public/` wins over a route at the same path, so leaving it would have made
 * this route dead code that looked live.
 *
 * The path stays `/sw.js` because that is what is already registered on every
 * installed device. A service worker's scope is its own directory, so `/sw.js`
 * scopes to `/` and needs no `Service-Worker-Allowed` header.
 */

// `force-dynamic` so the body is regenerated rather than baked into a static
// export — the build id has to be the one this deploy was built with.
export const dynamic = 'force-dynamic';

const source = (buildId: string) => `// Generated by app/sw.js/route.ts — do not edit a copy of this by hand.
const VERSION = ${JSON.stringify(buildId)};
const STATIC = 'bmb-sw-static-' + VERSION;
const PAGES = 'bmb-sw-pages-' + VERSION;
const MINE = [STATIC, PAGES];

self.addEventListener('install', () => {
  // Nothing is precached. The caches fill from real traffic, which is what
  // makes a stale entry impossible: anything in them was served to this
  // document while it was current.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Delete every cache this worker owns from an older build. The prefix test
    // is deliberately narrow: the DOWNLOADS buckets (bmb-downloads-*) are the
    // user's own files and must never be touched here.
    const names = await caches.keys();
    await Promise.all(
      names
        .filter((n) => n.startsWith('bmb-sw-') && !MINE.includes(n))
        .map((n) => caches.delete(n)),
    );
    await self.clients.claim();
  })());
});

/** Four things never enter a cache, and each would be a real bug. */
function cacheable(request, url) {
  // A cached POST is not a thing.
  if (request.method !== 'GET') return false;
  // Enclosure audio, relay traffic, third-party artwork. Not ours to hold, and
  // downloads have their own buckets with their own lifetime.
  if (url.origin !== self.location.origin) return false;
  // A cached /api/feed serves a stale episode list, and /api/live-status would
  // report a finished show as live.
  if (url.pathname.startsWith('/api/')) return false;
  return true;
}

async function putIfOk(cacheName, request, response) {
  // A cached 404 or 502 outlives the outage that produced it. An opaque or
  // cross-origin response cannot be read back usefully either.
  if (!response || !response.ok || response.type !== 'basic') return;
  if ((response.headers.get('cache-control') || '').includes('no-store')) return;
  const cache = await caches.open(cacheName);
  await cache.put(request, response.clone());
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (!cacheable(request, url)) return; // straight to the network, as before

  // /_next/static/* is CONTENT-HASHED, so a given URL's bytes never change and
  // a cached copy cannot go stale. Cache-first here is what makes the rule
  // below work offline: the last document's chunks are still present.
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith((async () => {
      const hit = await caches.match(request);
      if (hit) return hit;
      const res = await fetch(request);
      await putIfOk(STATIC, request, res);
      return res;
    })());
    return;
  }

  // EVERYTHING ELSE IS NETWORK-FIRST, and the cache is used ONLY when the fetch
  // rejects. A reader with a connection is therefore never served a stale
  // document, so a stale document can never reference dead chunk hashes while
  // online — which is the failure the old public/sw.js comment warned about.
  event.respondWith((async () => {
    try {
      const res = await fetch(request);
      await putIfOk(PAGES, request, res);
      return res;
    } catch (err) {
      const hit = await caches.match(request);
      if (hit) return hit;
      throw err;
    }
  })());
});
`;

export function GET() {
  return new Response(source(BUILD_ID), {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      // Browsers cap a service worker script at 24h regardless, but say it
      // plainly: this file must be re-read, or a deploy's cleanup never runs.
      'Cache-Control': 'no-cache, must-revalidate',
    },
  });
}
