import { loadPlaylistPage, tripPiBreaker } from '@/lib/podcast-meta';
import type { Podcast } from '@/lib/types';

/**
 * The curated playlist collection: which feed it comes from, and how to read it.
 *
 * Browser-only — it calls `fetch` against this app's own API routes and trips
 * the client-side Podcast Index breaker. It lived at the top of
 * `components/home-page.tsx` while `<HomePage>` was the only surface that
 * showed a collection; `/playlists` is now the second, and `<HomePage>` still
 * needs `loadCollection` for its `?publisher=` cold restore and for a
 * third-party publisher feed a visitor found by searching. Two copies of this
 * fetch had already drifted apart once inside that one file.
 */

/**
 * ChadF's musicL **publisher** feed — the app's single curated entry point.
 *
 * It is a publisher feed rather than a list of playlist URLs, and that is the
 * whole point: the publisher lists its children, so a playlist added there
 * appears here the same day with no code change. StableKraft takes the other
 * road and hardcodes its twelve playlist URLs — in five separate places, which
 * have already drifted apart from each other and from the collection's own
 * FEEDS.md, and each of which lists a different subset.
 *
 * Nothing else in the app is curated; the rest is search. One constant is the
 * smallest thing that makes a collection discoverable without pasting a URL,
 * and `/api/publisher` was already able to render it.
 */
export const MUSICL_PUBLISHER_URL =
  'https://raw.githubusercontent.com/ChadFarrow/chadf-musicl-playlists/refs/heads/main/docs/chadf-musicl-publisher.xml';

/**
 * Playlists shown on this site alongside the publisher feed's own children.
 *
 * The publisher feed is ChadF's and lists what ChadF publishes; these are
 * playlists somebody else made, on somebody else's host, that this site chooses
 * to surface anyway. They deliberately live HERE and not in that feed — putting
 * a third party's playlist in a feed titled "playlists I've made" would make
 * every app that reads it repeat a false claim about authorship, and that feed
 * is not ours to change the meaning of.
 *
 * The cost is the one this module already accepted for `MUSICL_PUBLISHER_URL`:
 * a URL in the codebase needs a deploy to change. Keep this list SHORT for that
 * reason — a playlist its own publisher lists is better reached through a
 * publisher feed, which needs no deploy at all.
 */
const EXTRA_PLAYLIST_URLS: readonly string[] = [
  // "Christmas" — Sir Libre, 36 tracks, generated by v4vmusic.com. Not in
  // Podcast Index, so a keyword search cannot reach it and this is the only
  // route to it short of pasting the URL.
  'https://v4vmusic.com/playlist/508a029b-020f-4334-9704-e0a9a5f800fb.xml',
];

/** One feed URL → the `Podcast` it resolves to, or null. */
async function resolveFeedUrl(url: string): Promise<Podcast | null> {
  try {
    // `/api/search` with a URL is the app's existing "resolve this feed" door:
    // Podcast Index first, the raw RSS when PI does not hold it, and the
    // blank-record repair when PI holds it badly. Re-implementing any of that
    // here is how the two would drift.
    const res = await fetch(`/api/search?q=${encodeURIComponent(url)}`);
    if (!res.ok) return null;
    return (await res.json()).feeds?.[0] ?? null;
  } catch {
    return null;
  }
}

/**
 * A publisher feed's children, plus this site's extras when it is OUR feed.
 *
 * Shared by three callers — `/playlists`, the `?publisher=` cold restore, and
 * `handleSelect` on a publisher row found by searching.
 *
 * **The extras attach only to `MUSICL_PUBLISHER_URL`.** `handleSelect` runs for
 * ANY publisher feed, including one a visitor found by searching, and injecting
 * this site's additions into somebody else's collection would misrepresent
 * their feed to the person reading it.
 *
 * Returns null when the collection itself could not be loaded, which the caller
 * renders as an error. An individual extra that fails to resolve is dropped
 * instead — the same treatment `/api/publisher` gives a child of its own that
 * resolves to nothing.
 *
 * **`listed` is how many entries this collection SHOULD hold**, against
 * `feeds.length` for how many resolved. They disagree when a child could be
 * neither found in Podcast Index nor read from its RSS — routine while PI is
 * rate limiting, and invisible without this, because a surface holding only the
 * survivors will print that number as a fact about the collection. A caller
 * that states a count must compare the two first.
 *
 * **`null` covers a THROWN failure too, not just a non-ok status.** A bare
 * `fetch` rejects when the device is offline or the request is blocked, so for
 * the life of this function the doc line above was false and each caller had to
 * carry its own `try`/`catch` to make it true — two copies at the time, and a
 * third surface would have been one forgotten `catch` away from a page stuck on
 * "loading" forever, with an unhandled rejection as the only trace. The guard
 * belongs with the promise it describes.
 */
export interface Collection {
  feeds: Podcast[];
  /** How many entries the collection names — see the note above. */
  listed: number;
  /**
   * True when the rows were read from RSS because Podcast Index was rate
   * limiting. The list is COMPLETE and the feeds are authoritative, but every
   * record is `isPreview` — no PI id, no guid — so the rows stamp "NOT IN PI"
   * and `<FavHeart>` withholds the favorite. A surface that renders it must say
   * so: a whole page of missing hearts is otherwise indistinguishable from a
   * feature that does not exist, which is the failure this repo has already
   * paid for on the BOOST button.
   */
  couldNotAskPi: boolean;
}

export async function loadCollection(feedUrl: string): Promise<Collection | null> {
  try {
    const res = await fetch(`/api/publisher?feedUrl=${encodeURIComponent(feedUrl)}`);
    if (!res.ok) {
      // A 5xx is the route saying PI itself is down — its probe is deliberately
      // uncaught. Trip the breaker rather than rendering an empty collection.
      if (res.status >= 500) tripPiBreaker();
      return null;
    }
    const body = await res.json();
    const own: Podcast[] = body.feeds ?? [];
    // Falls back to what arrived rather than to 0: an older deploy of the route
    // does not send `listed`, and a 0 there would read as "everything is
    // missing" on a collection that is perfectly complete.
    const ownListed: number = typeof body.listed === 'number' ? body.listed : own.length;
    const couldNotAskPi: boolean = body.couldNotAskPi === true;
    if (feedUrl !== MUSICL_PUBLISHER_URL || !EXTRA_PLAYLIST_URLS.length) {
      return { feeds: own, listed: ownListed, couldNotAskPi };
    }

    // Deduped by feed URL: a playlist the publisher feed later lists itself must
    // not appear twice, and that is the likely end state for anything here.
    const already = new Set(own.map((f) => f.url).filter(Boolean));
    const wanted = EXTRA_PLAYLIST_URLS.filter((u) => !already.has(u));
    if (!wanted.length) return { feeds: own, listed: ownListed, couldNotAskPi };
    const extras = await Promise.all(wanted.map(resolveFeedUrl));
    return {
      feeds: [...own, ...extras.filter((f): f is Podcast => f !== null)],
      // The extras are named by this file, so they count toward what the
      // collection should hold exactly as the publisher's own children do.
      listed: ownListed + wanted.length,
      couldNotAskPi,
    };
  } catch {
    return null;
  }
}

/**
 * An offset past the last ref of any playlist, so `/api/playlist` answers with
 * its `total` and resolves NO rows.
 *
 * Mirrors `MAX_PLAYLIST_REFS` in `lib/feed-xml.ts`, which is the ceiling the
 * parser itself applies — a copy rather than an import because that module
 * pulls in `nostr-tools`, which is a lot of bundle to carry for one number.
 * **Drift degrades safely in the one direction it can go**: if that cap is ever
 * raised above this, a long playlist resolves a one-row page instead of none,
 * which costs one extra Podcast Index call and returns the identical `total`.
 */
const PAST_LAST_REF = 5000;

/**
 * The deduped track count for one playlist, or null when we could not ask.
 *
 * `/api/playlist` answers `total` for the WHOLE list on every page, so the
 * cheapest way to ask "how long is this?" is to ask for a page that does not
 * exist: past the last ref the route returns `total: refs.length` from an early
 * branch that never calls `batchEpisodes`. The count is the same number either
 * way — it is `refs.length` after the parser's dedupe, which is what a reader
 * sees when they open the list.
 *
 * **The saving is the point, not a micro-optimisation.** A collection is ~10
 * rows and this runs once per row, so asking for a REAL page (`limit: 1`) spent
 * ~20 Podcast Index calls on a line of small text — one `piRecordFor` plus one
 * `batchEpisodes` per row, on top of `/api/publisher`'s own fan-out. That was
 * enough to rate-limit PI from a few page reloads, and a rate-limited PI makes
 * `/api/publisher` drop the children it cannot resolve, so the collection came
 * back SHORT and the page stated the short number as fact. The count was paying
 * for itself in wrong counts. This halves it to the one `piRecordFor` the route
 * makes unconditionally.
 *
 * **Returns null rather than 0 on every failure.** That route is rate limited
 * to 30/min per IP, so a 429 on a household IP shared by a phone and a desktop
 * is ordinary. Zero would render as an empty playlist, which is a claim about
 * the feed rather than about our request — the same distinction `couldNotAsk`
 * draws inside the route.
 */
export async function playlistTrackCount(feedUrl: string): Promise<number | null> {
  try {
    const { total } = await loadPlaylistPage({ feedUrl, offset: PAST_LAST_REF, limit: 1 });
    return typeof total === 'number' ? total : null;
  } catch {
    return null;
  }
}
